version: '3.8'
services:
  web:
    image: web-app:latest-snapshot
    container_name: web-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./application.yml:/app/config/application.yml
      - ./log:/app/log
  webui:
    image: webui-app:latest-snapshot
    container_name: webui-app
    restart: always
    ports:
      - "9091:80"
